name: Cross platform build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    name: Linux Build (O0 & O3)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y binutils

    - name: Build and run with -O0 and -O3
      run: |
        for OPT in O0 O3; do
          echo "=== Building with -$OPT ==="
          cmake -S . -B build_$OPT -DCMAKE_CXX_FLAGS="-$OPT" -DCMAKE_BUILD_TYPE=Release
          cmake --build build_$OPT

          echo "--- Running program (-$OPT) ---"
          ./build_$OPT/main

          echo "--- size (main -$OPT) ---"
          size ./build_$OPT/main

          echo "--- objdump -t (main -$OPT) ---"
          objdump -t ./build_$OPT/main

          echo "--- readelf -S (main -$OPT) ---"
          readelf -S ./build_$OPT/main
        done

  build-windows:
    name: Windows Build (O0 & O3)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run with -O0 and -O3
      shell: bash
      run: |
        for OPT in O0 O3; do
          echo "=== Building with /$OPT ==="
          cmake -S . -B build_$OPT -DCMAKE_CXX_FLAGS="/$OPT" -DCMAKE_BUILD_TYPE=Release
          cmake --build build_$OPT --config Release

          exe_path="build_$OPT/Release/main.exe"
          echo "--- Running program (/ $OPT) ---"
          "$exe_path"

          echo "--- objdump -t (main.exe /$OPT) ---"
          objdump -t "$exe_path" || echo "objdump not available"

          echo "--- nm (main.exe /$OPT) ---"
          nm "$exe_path" || echo "nm not available"
        done

  build-macos:
    name: macOS Build (O0 & O3)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run with -O0 and -O3
      run: |
        for OPT in O0 O3; do
          echo "=== Building with -$OPT ==="
          cmake -S . -B build_$OPT -DCMAKE_CXX_FLAGS="-$OPT" -DCMAKE_BUILD_TYPE=Release
          cmake --build build_$OPT

          echo "--- Running program (-$OPT) ---"
          ./build_$OPT/main

          echo "--- size (main -$OPT) ---"
          size ./build_$OPT/main || echo "size not available"

          echo "--- nm (main -$OPT) ---"
          nm ./build_$OPT/main || echo "nm not available"

          echo "--- otool -l (main -$OPT) ---"
          otool -l ./build_$OPT/main || echo "otool not available"
        done
