name: Cross platform O0/O3 builds with debug symbols

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux:
    name: Linux Build and Run (O0 & O3)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y binutils

    - name: Build -O0
      run: |
        cmake -S . -B build_O0 -DCMAKE_CXX_FLAGS_INIT="-O0 -g" -DCMAKE_BUILD_TYPE=Release
        cmake --build build_O0

    - name: Run -O0
      run: |
        ./build_O0/main
        echo "--- size ---"
        size ./build_O0/main
        echo "--- nm -C ---"
        nm -C ./build_O0/main
        echo "--- objdump -t ---"
        objdump -t ./build_O0/main
        echo "--- readelf -S ---"
        readelf -S ./build_O0/main

    - name: Build -O3
      run: |
        cmake -S . -B build_O3 -DCMAKE_CXX_FLAGS_INIT="-O3 -g" -DCMAKE_BUILD_TYPE=Release
        cmake --build build_O3

    - name: Run -O3
      run: |
        ./build_O3/main
        echo "--- size ---"
        size ./build_O3/main
        echo "--- nm -C ---"
        nm -C ./build_O3/main
        echo "--- objdump -t ---"
        objdump -t ./build_O3/main
        echo "--- readelf -S ---"
        readelf -S ./build_O3/main

  macos:
    name: macOS Build and Run (O0 & O3)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build -O0
      run: |
        cmake -S . -B build_O0 -DCMAKE_CXX_FLAGS_INIT="-O0 -g" -DCMAKE_BUILD_TYPE=Release
        cmake --build build_O0

    - name: Run -O0
      run: |
        ./build_O0/main
        echo "--- size ---"
        size ./build_O0/main || echo "size not available"
        echo "--- nm -C ---"
        nm -C ./build_O0/main || echo "nm not available"
        echo "--- otool -l ---"
        otool -l ./build_O0/main || echo "otool not available"

    - name: Build -O3
      run: |
        cmake -S . -B build_O3 -DCMAKE_CXX_FLAGS_INIT="-O3 -g" -DCMAKE_BUILD_TYPE=Release
        cmake --build build_O3

    - name: Run -O3
      run: |
        ./build_O3/main
        echo "--- size ---"
        size ./build_O3/main || echo "size not available"
        echo "--- nm -C ---"
        nm -C ./build_O3/main || echo "nm not available"
        echo "--- otool -l ---"
        otool -l ./build_O3/main || echo "otool not available"

  windows:
    name: Windows Build and Run (O0 & O3 using Clang + MinGW)
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2 and LLVM
      run: |
        choco install msys2 -y
        choco install llvm -y

    - name: Install MSYS2 packages
      run: |
        C:/tools/msys64/usr/bin/bash.exe -lc "
          pacman -Sy --noconfirm \
            mingw-w64-x86_64-toolchain \
            cmake \
            make \
            binutils
        "

    - name: Build -O0
      run: |
        C:/tools/msys64/usr/bin/bash.exe -lc "
          export PATH=/mingw64/bin:\$PATH

          mkdir -p build_O0 && cd build_O0
          cmake -G 'MinGW Makefiles' -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS='-O0 -g' ..
          cmake --build .
        "

    - name: Run -O0
      run: |
        C:/tools/msys64/usr/bin/bash.exe -lc "
          export PATH=/mingw64/bin:\$PATH
          cd build_O0

          ./main.exe

          echo '--- size ---'
          size ./main.exe

          echo '--- nm -C ---'
          nm -C ./main.exe

          echo '--- objdump -t ---'
          objdump -t ./main.exe
        "

    - name: Build -O3
      run: |
        C:/tools/msys64/usr/bin/bash.exe -lc "
          export PATH=/mingw64/bin:\$PATH

          mkdir -p build_O3 && cd build_O3
          cmake -G 'MinGW Makefiles' -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS='-O3 -g' ..
          cmake --build .
        "

    - name: Run -O3
      run: |
        C:/tools/msys64/usr/bin/bash.exe -lc "
          export PATH=/mingw64/bin:\$PATH
          cd build_O3

          ./main.exe

          echo '--- size ---'
          size ./main.exe

          echo '--- nm -C ---'
          nm -C ./main.exe

          echo '--- objdump -t ---'
          objdump -t ./main.exe
        "
